## Project 1: Iris Flower Guesser

Building a small and simple project with a tiny dataset called `iris.csv`. It's a small and tiny dataset about flowers completely for beginners. First we'll look into the dataset and check how it looks like for loading the csv file we're going to use `pandas` module

In [2]:
!pip install pandas

  Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 60.6 kB/s eta 0:00:00 kB/s eta 0:00:01:01
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 1.5 MB/s eta 0:00:00m eta 0:00:010:00:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.9/507.9 kB 1.5 MB/s eta 0:00:001.9 MB/s eta 0:00:01
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)


In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('Iris.csv')

In [6]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


You can see above the dataset contains mainly 5 columns like `SepalLengthCm`, `SepalWidthCm`, `PetalLengthCm`, `PetalWidthCm` and `Species`.

So, by using this simple dataset we'll create our simple project Flower Guesser. For inputs we will use:

input: 2 measurements like petal length and petal width

output: by using this inputs we'll guess the flower species

So first we will check for how many species there in dataset

In [7]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

So, there is three species so our goal is to create a flower guesser model to guess the flower species based on the `petal width` and `petal height` so, let's start the process.

First we'll install the torch

In [8]:
!pip install torch

  Using cached filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.

In [62]:
#importing necessary libararies
import torch
import torch.nn as nn

After this we need to assign the input and output values by using dataset like below

In [63]:
x = df[['PetalLengthCm', 'PetalWidthCm']].values

In [64]:
x

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

Now we taken the `x` as our input next we need to taken our species as our output before that we're going to create a new column to map 0, 1, 2 to our species 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'. For, that we're going to use the below code:

In [65]:
#mapping species names to num
names_to_num = {"Iris-setosa":0, "Iris-versicolor":1, "Iris-virginica":2}

#creating new column and adding the data based on species to the dataframe using pandas
df['species_to_num'] = df['Species'].map(names_to_num)

In [22]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,species_to_num
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0


so, the mapping done next we will assign this values to our output variable `y`

In [66]:
y = df['species_to_num'].values

In [67]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Now, we taken our inputs and outputs next we're going to convert this to tensors like below

In [68]:
x = torch.tensor(x, dtype=torch.float32)

x

In [69]:
y = torch.tensor(y, dtype=torch.long)

In [70]:
y

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

ok now we have inputs and outputs next we will build a model like below

In [71]:
# building the model
class FlowerGuesser(nn.Module):
    def __init__(self):
        super(FlowerGuesser, self).__init__()
        self.layer = nn.Linear(2, 3) #2 inputs petal width and height and 3 outputs 1, 2, 3

    def forward(self, x):
        x = self.layer(x)
        return x

In [72]:
model = FlowerGuesser()

now we created a model next we need to train it

In [73]:
#training the model
criterion = nn.CrossEntropyLoss()

In [74]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [75]:
for epoch in range(200):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1)%50 == 0:
        print(f"Try {epoch+1}, Mistake: {loss.item():.4f}")

Try 50, Mistake: 0.7764
Try 100, Mistake: 0.6498
Try 150, Mistake: 0.5727
Try 200, Mistake: 0.5214


Training completed next we're going to save the model

In [76]:
torch.save(model.state_dict(), "flower_guesser.pth")

Now we successfully save the model, next we will load the model and use it on our program

In [77]:
#loading the saved model
trained_model = FlowerGuesser()
trained_model.load_state_dict(torch.load("flower_guesser.pth"))

<All keys matched successfully>

In [78]:
trained_model.eval()

FlowerGuesser(
  (layer): Linear(in_features=2, out_features=3, bias=True)
)

So, finally we trained the model next we're going to test with some samples

In [79]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,species_to_num
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0


In [80]:
test_x = torch.tensor([[5.1, 2.3]], dtype=torch.float32)

In [81]:
guesses = trained_model(test_x)

In [82]:
prediction = torch.argmax(guesses, dim=1)

In [83]:
print(prediction.item())

2


In [84]:
test_X = x[:5]
real_y = y[:5]
guesses = trained_model(test_X)
predictions = torch.argmax(guesses, dim=1)
print("Petal Length, Width | Real Answer | Guess")
for i in range(5):
    print(f"{test_X[i].tolist()} | {real_y[i].item()} | {predictions[i].item()}")

Petal Length, Width | Real Answer | Guess
[1.399999976158142, 0.20000000298023224] | 0 | 0
[1.399999976158142, 0.20000000298023224] | 0 | 0
[1.2999999523162842, 0.20000000298023224] | 0 | 0
[1.5, 0.20000000298023224] | 0 | 0
[1.399999976158142, 0.20000000298023224] | 0 | 0
