## Project 2: Predicting Diabetes

For this project we're going to use one large dataset comparing to `iris_dataset`. First we will look into the data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In the diabetes table 1 means `diabetes patient` and 0 means `healthy person`. we're going to take this 2 as outputs and other 8 columns as inputs. Then we're going to predict that the person have `diabetes` or `not`.

In [4]:
x = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']].values

In [5]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]],
      shape=(768, 8))

In [6]:
y = df['Outcome'].values

In [7]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

Next, we're going to convert the input and output to tensors like below:, before that we're going to import the torch dependencies

In [8]:
import torch
import torch.nn as nn

In [9]:
#converting to tensor
x = torch.tensor(x, dtype=torch.float32)

In [10]:
x

tensor([[  6.0000, 148.0000,  72.0000,  ...,  33.6000,   0.6270,  50.0000],
        [  1.0000,  85.0000,  66.0000,  ...,  26.6000,   0.3510,  31.0000],
        [  8.0000, 183.0000,  64.0000,  ...,  23.3000,   0.6720,  32.0000],
        ...,
        [  5.0000, 121.0000,  72.0000,  ...,  26.2000,   0.2450,  30.0000],
        [  1.0000, 126.0000,  60.0000,  ...,  30.1000,   0.3490,  47.0000],
        [  1.0000,  93.0000,  70.0000,  ...,  30.4000,   0.3150,  23.0000]])

In [11]:
y = torch.tensor(y, dtype=torch.long)

In [12]:
y

tensor([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,

For this model we're going to add some more layers to train it well the 

first layer will change `8` inputs to `16` helpers

then the second layer will change `16` inputs to `8` helpers

then again to the last and third layer it will change the `8` inputs to `2` outputs

and here we're going to add one ReLU() also for better learning.

In [44]:
class DiabeticPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(8, 16) #8 inputs to 16 helpers
        self.layer2 = nn.Linear(16, 8) #16 inputs to 8 helpers
        self.layer3 = nn.Linear(8, 2) # 8 inputs to 2 outputs
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.layer3(x)
        return x

In [45]:
model = DiabeticPredictor()

In [46]:
criterion = nn.CrossEntropyLoss()

In [47]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [48]:
for epoch in range(100000):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1)%5000 == 0:
        print(f"Try {epoch+1}, Mistake: {loss.item():.4f}")

Try 5000, Mistake: 0.3261
Try 10000, Mistake: 0.3134
Try 15000, Mistake: 0.3063
Try 20000, Mistake: 0.3038
Try 25000, Mistake: 0.3057
Try 30000, Mistake: 0.3053
Try 35000, Mistake: 0.3013
Try 40000, Mistake: 0.3002
Try 45000, Mistake: 0.3001
Try 50000, Mistake: 0.2979
Try 55000, Mistake: 0.2950
Try 60000, Mistake: 0.2938
Try 65000, Mistake: 0.2938
Try 70000, Mistake: 0.2928
Try 75000, Mistake: 0.2943
Try 80000, Mistake: 0.2924
Try 85000, Mistake: 0.2925
Try 90000, Mistake: 0.2917
Try 95000, Mistake: 0.2920
Try 100000, Mistake: 0.2918


Predicting the result

In [49]:
test_X = x
real_y = y
guesses = model(test_X)
predictions = torch.argmax(guesses, dim=1)
total = len(x)
crct_predictions = 0
for i in range(len(x)):
    if real_y[i].item() == predictions[i].item():
        crct_predictions+=1
print(f"Total: {total} | Correct predictions: {crct_predictions}")
percentage = (crct_predictions/total)*100
print(f"Percentage: {percentage}")

Total: 768 | Correct predictions: 662
Percentage: 86.19791666666666
